### ISSUE TITLE
Upgrades.json in BHoMUpgrader41 appear to duplicate those in Upgrades.json in BHoMUpgrader40

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/Versioning_Toolkit#131]
#### Description:
I did a full removal and then installation using the alpha from 210107 and noticed that
C:\ProgramData\BHoM\Upgrades\BHoMUpgrader41\Upgrades.json appears to duplicate all upgrades in C:\ProgramData\BHoM\Upgrades\BHoMUpgrader40\Upgrades.json

**Comment by adecler** [comment]
This is fixed by https://github.com/BHoM/Versioning_Toolkit/pull/130
