### ISSUE TITLE
Plan for storing BHoM version of object as part of serialisation.

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Versioning_Toolkit#140]
This was discussed previously as a need for two purposes.

1. was with regarding to versioning - where the version of the schema used at time of serialisation will assist in the deserialisation process, and 
2.  regarding the recent ISpecification work that is being carried out. Here the version of the schema stored will be essential to allow a specification to similarly be versioned and perform an additional check of objects on application of spec to provide warnings if version is different from that at time of authoring.

@adecler as discussed there are complexities in introducing this feature - so can you start to capture some of the plans to be developed here. 
I think it was agreed through discussion with @IsakNaslundBh that any changes would need to span a couple of milestones to ensure backwards compatibility. So good to map out any steps that may need to be taken in short, mid and longer term. 
Thanks

Raised issue here as made sense regarding versioning - naturally issues may be needed in Versioning_Engine and Serialisation_Engine etc. in core BHoM_Engine. Happy for issues to be raised/migrated as makes sense @adecler 

@IsakNaslundBh @alelom @FraserGreenroyd FYI

**Comment by alelom** [comment]
Thanks for raising this @al-fisher .

**Comment by adecler** [comment]
I thought this had already been settled and agreed. The plan was in two steps:
- Add ability to extract BHoM version from json if available: already done in https://github.com/BHoM/BHoM_Engine/pull/2269
- Save the BHoM version during serialisation after producing the 4.1 beta: code already written in https://github.com/BHoM/BHoM_Engine/pull/2269 waiting to be uncommented in 4.2 (see https://github.com/BHoM/BHoM_Engine/blob/master/Versioning_Engine/Modify/AddVersion.cs)

I have added an issue in the BHoM_Engine as a reminder: https://github.com/BHoM/BHoM_Engine/issues/2346

There is no work required on the versioning toolkit itself so closing this.
