### ISSUE TITLE
Add 4.1 dataset to .ci tests for BHoMBot

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Versioning_Toolkit#155]
@adecler I couldn't find the process for setting up the new datasets for the `.ci/code` part of this toolkit. Could you handle it for this occasion and link me to a wiki for the next milestone? :smile:

Happy to just turn on 4.1 (3.3, 4.0, and 4.1) for PR checks for now unless you think there's a gain to be had by turning on one of the other's as well (given we closed out all 3.3 and 4.0 issues in the last milestone and adding this check should ensure we don't get any 4.1 issues creeping in!). So if you want us to start tackling 3.2 versioning issues I'm happy for us to turn that on now. Otherwise, happy to stick with just doing 3.3 onwards for the time being. Will let you decide on this one :smile:

If this could be done reasonably soon that'd be great, it'll close out the CI/CD issues needed for the setting up of this milestone while everyone is busy doing their coordination sessions :smile:

**Comment by adecler** [comment]
Thanks @FraserGreenroyd .
I have added the dataset in the PR linked above. You can find the procedure [here](https://github.com/BHoM/Versioning_Toolkit/wiki/Procedure-for--creating-the-test-datasets-for-versioning-CI%5CCD).

The PR already adds the version 4.1 in the list of datasets to test but you will probably have to do the same in your procedure if you are already tested each version individually. 

I wouldn't worry about 3.2. It would make sense to test a limited number of older versions anyways. I was thinking about testing 4 versions so we are covering one year. BHoM Analytics tells us that less than 10% are still on version 3.3 so this should be good enough.
