### ISSUE TITLE
Check against the methods not being objects on deserialisation

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Versioning_Toolkit#172]
#### Description:

Following the debugging session between @adecler and @pawelbaran, turned that the latter decided to break Versioning by putting a string instead of an object to method versioning section of the .json file - safety net against it would be nice.

![image](https://user-images.githubusercontent.com/26874773/127468670-ef3fd12e-ecf8-4a71-9c7b-85d57a19064a.png)

**Comment by adecler** [comment]
Conclusions from a chat with @FraserGreenroyd:
- The programs needs to stop if the input is incorrect and the error message is pretty explicit so not sure how to improve on this
- The upgrader is meant to be used within the UI and the CI/CD and not as a standalone tool for general usage. So it feels that any direct usage would be done by experts that wouldn't be phased by the type of error message provided
