### ISSUE TITLE
Verification: Versioning of Adapters is not tested by the verification

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Versioning_Toolkit#187]
#### Definition of the test :

The current versioning test sets does not contain information about any of the Adapters and their constructors. Should either add a new testset with all constructors, or add them to the method checks.

**Comment by FraserGreenroyd** [comment]
Have added verification elements for adapters, and added adapter datasets for 3.3 onwards by installing old betas.

Need to run through and check to see how versioning likes those old adapters and make sure they do version correctly and then should be good to go with this issue.

Currently pushed to a branch.
