### ISSUE TITLE
Versioning_Toolkit: Rebuilding does not work

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Versioning_Toolkit#32]
#### Description:

The otherwise simple operation of re-building the toolkit and then BHoM_UI does not always update the Versioning_Toolkit.

To make sure that the new version of versioning toolkit is used I have needed to delete the build folder in Versioning_Toolkit and from `%appdata%`, to then rebuild Verseioning_Toolkit and BHoM_UI to receive the changes.

not a huge bug but very annoying as it is not always obvious that it's happening.

**Comment by adecler** [comment]
@kThorsager , sorry for asking this but are you sure you didn't have one of the UIs open when compiling ?

During my development of the versioning toolkit, I have compiled hundreds of times and I didn't have that problem once. I have tested again just to make sure and everything is working as expected. If this happens again, can you make sure you don't have BHoM processes still running in task manager ? The only thing I can think of is if the BHoMUpgraders were not closed properly when the UI is closed although I have never had that myself.

**Comment by kThorsager** [comment]
Won't dare to say 100% sure, 
I'll try to reproduce the issue in a consistent way and see if I can get any wiser

**Comment by adecler** [comment]
closing for now
