### ISSUE TITLE
Versioning_Toolkit: Does not work for objects created in canvas by old component

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Versioning_Toolkit#34]
#### Description:
While the versioning works for objects on de-serialisation, it does not work on objects which are created in the canvas (with old code), and presumably works works for the `IElement` upgrade as the components which created the objects are also upgraded.

Not sure if this is within the scope of what Versioning is suppose to capture, but it is worth mentioning that it does not do this, as it does contain type converters and upgrades objects otherwise.

BHoM 2.3 component for Level
![image](https://user-images.githubusercontent.com/53530468/75546323-2f76f580-5a20-11ea-9215-60f54824a62a.png)
As the Create component is not upgraded and the Versioning_Toolkit works on serialisation(?) it is never fixed

**Comment by adecler** [comment]
@kThorsager , Can you provide the file for the example above?

**Comment by kThorsager** [comment]
Sorry of course:
https://burohappold.sharepoint.com/:u:/s/BHoM/EWnrERqNId9MnQuEPB5hGGwB1W6zcydu4JfSJpDmqgBtgg?e=5snbbS

**Comment by adecler** [comment]
After looking into this in more details, I don't see it as a bug or even a missing feature.

The old `Create.Level` component you have in your example corresponds a deprecated method that still exists in the code. Same thing for the `oM.Architecture.Elements.Level` class. It is deprecated but still exists in the code. 

Say output of `Create.Level` was plugged into another deprecated component that was expecting a `oM.Architecture.Elements.Level` as input. If we had done the upgrade of the output, the old script would actually break. 

Things will be very different once the deprecated method is completely removed from the code. Then the component, will be updated and the output will be a `oM.Geometry.SeettingOut.Level` as expected.

I am closing this to keep my task list up to date but feel free to reopen if you disagree with me.

@al-fisher , @IsakNaslundBh , Let me know if you disagree with my explanation.
