### ISSUE TITLE
Provide conversion from create methods to auto-constructor

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Versioning_Toolkit#35]
#### Description:

To be able to safely remove/delete Create methods acting as simple property assignment methods, we need the version Toolkit to automatically detect this and "upgrade" them to a Property initialiser.

Example:

```
        [Deprecated("3.1", "Replaced by Autogenerated property assignment method")]
        public static Panel Panel(List<Edge> externalEdges, List<Opening> openings = null, ISurfaceProperty property = null, string name = "")
        {
            return new Panel
            {
                ExternalEdges = externalEdges,
                Openings = openings ?? new List<Opening>(),
                Property = property,
                Name = name
            };
        }
```

Should basically be replaced.

Related and noting from the Framework call, some Create methods will not be able to be upgraded, and this might/will be fine. As an example:

```
        [Deprecated("3.1", "Method that use a mixture of geometry and objects between edges and openings removed.")]
        public static Panel Panel(List<Edge> externalEdges, List<ICurve> openings = null, ISurfaceProperty property = null, string name = "")
        {
            List<Opening> pOpenings = openings != null ? openings.Select(o => Create.Opening(o)).ToList() : new List<Opening>();
            return Panel(externalEdges, pOpenings, property, name);
        }
```
Is simply deprecated with the intention to remove this method altogether. If versioning _could_ be done for this, that is ofc good, but not a priority. Priority is basically just to have any method that is doing nothing except setting properties to an object being able to be deprecated/deleted and replaced with the property assignment. (A bit lengthy description for something I think hope is quite clear! 😄 )

**Comment by adecler** [comment]
@IsakNaslundBh , this was actually done in https://github.com/BHoM/BHoM_UI/pull/164
I have tested again deleting a Create method and it works well for me. 
Am I missing something ?

**Comment by adecler** [comment]
@IsakNaslundBh , now closing based on last week discussion.

**Comment by IsakNaslundBh** [comment]
Yes, thank @adecler . Tested on Robot_Toolkit myself, and all seem fine!
