### ISSUE TITLE
Cover the case where an entire namespace is renamed

### ISSUE THREAD

**Issue by alelom** [BHoM/Versioning_Toolkit#37]
#### Description:

As discussed in call with @al-fisher, @IsakNaslundBh, @FraserGreenroyd

Versioning should cover this case, for example when we rename:

> - oM:
>    - BH.oM.Adapter.Revit -> BH.oM.External.Revit
>    - BH.oM.Adapter.GSA -> BH.oM.External.GSA
>    - BH.oM.Adapter.Dynamo -> BH.oM.External.Dynamo

> - Engine:
>    - BH.Engine.Adapter.Revit -> BH.Engine.External.Revit
>    - BH.Engine.Adapter.GSA -> BH.Engine.External.GSA

(from https://github.com/BHoM/BHoM_Adapter/issues/210)

and similar.

**Comment by adecler** [comment]
It should already have that capability. Is it not working for you?

**Comment by alelom** [comment]
Sorry, this was before we had our chat @adecler . I was asked to open this because others where convinced it wasn't there yet, and then I forgot to close. Closing now.
