### ISSUE TITLE
Versioning_Toolkit: Revit_Toolkit refactoring use case

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Versioning_Toolkit#47]
With the Revit_Toolkit refactoring and renaming in perspective, I made a list of cases that would be good to cover with Versioning_Toolkit:
- [ ] namespace renaming, incl. subnamespaces, 2 cases here:
    - `BH.oM.X => BH.oM.Y` and `BH.oM.X.abc => BH.oM.Y.abc` - change of the head namespace to work on all subnamespaces
    - `BH.oM.X => BH.oM.Y` and `BH.oM.X.abc => BH.oM.Y.def` - change of the head namespace and subnamespace independently
- [ ] `BH.oM.X => BH.oM.Y` and `BH.oM.Z => BH.oM.Y` - merging two namespaces into one (this will happen to the namespaces that are not exposed in the UI so can live without it)
- [ ] `BH.oM.X => BH.oM.Y => BH.oM.Z` - two subsequent namespace changes - will this require pairing both `BH.oM.X` with `BH.oM.Z` and `BH.oM.Y` with `BH.oM.Z`? Rather a theoretical question, but would be good to know if that is possible at all, and if so, how much hassle does it require

I believe some (all?) cases listed above are already resolved, while some of the may not be available any time soon. Both is fine, with this issue I am only trying to figure out what is possible and what is not. Could you please comment on that @adecler?

@al-fisher @IsakNaslundBh @alelom FYI

**Comment by adecler** [comment]
- [ ] First point is just missing a loop on the parts of the namespace that I thought I had done already but will be very quick to add. So no problem there.
- [x] That one is not a problem at all. There is no difference in the code if multiple namespaces are merged into a single one.
- [ ] Chaining across multiple BHoM versions still need some work but will be possible relatively soon. Chaining inside a quarter should be a non issue as you always update to the latest valid case. So, in the example of `BH.oM.X => BH.oM.Y => BH.oM.Z`, this should simply be added to the versioning toolkit as `BH.oM.X => BH.oM.Y` and `BH.oM.Y => BH.oM.Z`.
