### ISSUE TITLE
Versioning_Toolkit: Missing support for types that change properties

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Versioning_Toolkit#71]
#### Description:

Based on an example: in https://github.com/BHoM/Revit_Toolkit/pull/686 I have removed 3 `bool` properties from `RevitPullConfig` and added properties of type `RepresentationConfig` and `GeometryConfig`. Would be great to:
- be able to serialize/deserialize the type after change, with the new properties set to default
- make the components (particularly autoconstructors) not turn red after upgrade of BHoM

Personally I would say this is not a top priority, but rather _the more the better_ before 3.2 release.

#### Test file(s):

Sample on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FVersioning%5FToolkit%2FVersioning%5FToolkit%2DIssue71%2DChangedProperties) - same components from 3.1 and master before https://github.com/BHoM/Revit_Toolkit/pull/686 - would be great to support both (if possible).

**Comment by adecler** [comment]
I have switch the label to feature as a missing feature is not the same thing as a bug.

**Comment by adecler** [comment]
So you are saying that you removed 3 properties of a class and added two new properties of different type, right ?

I'll be honest, I think this is a case too complex for auto-versioning. What you can however do is to provide a converter method in the versioning toolkit that will upgrade the objects of that type. You can find an example of how to do that in https://github.com/BHoM/Versioning_Toolkit/blob/master/BHoMUpgrader30/Converter.cs

Full documentation on the wiki will be done before the end of the sprint but that should be enough to show you how to solve your current problem.

**Comment by pawelbaran** [comment]
The file gives a solid hint, but would be nice to go through an example together at some point. 

Since I am aiming to make this work before 3.2 release, I can also wait for the documentation - no rush. Will come back to that closer to the end of the Milestone. Thanks!

**Comment by adecler** [comment]
Documentation coming tomorrow . Will be a nice excuse to check if it is clear enough :smile:

**Comment by adecler** [comment]
Link tho the wiki:
https://github.com/BHoM/documentation/wiki/Versioning---How-to-modify-code-without-breaking-user-scripts

I believe this issue is now resolved but feel free to reopen if you disagree
