### ISSUE TITLE
Property name upgrade requires a full namespace check

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/Versioning_Toolkit#86]
#### Description:
If I want to add a Property name change to versioning like this:
```
"ToNew": {
      "BH.oM.Audience.ProfileParameters.NumRows" : "BH.oM.Audience.ProfileParameters.Rows"
    },
```
`NumRows` is replaced with the full namespace and new property name `BH.oM.Audience.ProfileParameters.Rows`

![Annotation 2020-07-22 114013](https://user-images.githubusercontent.com/6618854/88167052-23c6de00-cc10-11ea-8518-f849069803ad.png)

#### Steps to reproduce:
[This branch](https://github.com/BuroHappoldEngineering/Buildings_Toolkit/tree/Buildings_Toolkit-%2318-Property-renaming) includes a single simple property name change:
`NumRows` to Rows on the `ProfileParameters` object
The branch includes the Versioning_33.json

#### Expected behaviour:
Only the new property name is added to the new version.
In this case `NumRows` is replaced with `Rows`

#### Test file(s):

[This file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue86_PropertyNameChanges.gh?csf=1&web=1&e=31bA6B) contains a json string of the object with the old property name (as in the image above)

**Comment by adecler** [comment]
Fixed by https://github.com/BHoM/Versioning_Toolkit/pull/92
