### ISSUE TITLE
Versioning_Toolkit: Add ToNew methods for MeshResult classes

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Versioning_Toolkit#9]
The MeshResults have been upgraded in terms of some naming as well as some additional properties. https://github.com/BHoM/BHoM/issues/589

Need ToNew method for affected classes.

**Comment by adecler** [comment]
Is it still needed as we are now moving to 3.3 ?

**Comment by IsakNaslundBh** [comment]
Closing this as now old and no issues are currently being reported on MeshResults
